[package]
name    = "expenses_tracker"
version = "0.1.0"
authors = ["Ricardo Batista <ricardo.batista@hey.com>"]
edition = "2021"

[dependencies]
axum    = { version = "0.8.1" }
tokio   = { version = "1.43.0", features = ["full"] }
sqlx    = { version = "0.8.3", features = [ "runtime-tokio", "tls-rustls-ring-native-roots",
"postgres", "macros", "migrate" ] }

[dev-dependencies]
cucumber = { version = "0.21.1" }

[[test]]
name    = "main"
harness = true
